In [1]: from apps.likes_books.models import *

In [2]: User.objects.create(first_name = "Grant", last_name="Brooks", email="grant@brooks.com")
Out[2]: <User: User object>

In [3]: User.objects.create(first_name = "Harshada", last_name="kurahatti", email="Harshada@k.com")
Out[3]: <User: User object>

In [4]: User.objects.create(first_name = "Ali", last_name="Something", email="Ali@k.com")
Out[4]: <User: User object>

In [5]: Book.objects.create(name= "Harry Potter", uploader=User.objects.get(id=2))
Out[5]: <Book: Book object>

In [6]: Book.objects.create(name= "Sydney Sheldon", uploader=User.objects.get(id=2))
Out[6]: <Book: Book object>

In [7]: Book.objects.create(name= "Awesome Book", uploader=User.objects.get(id=1))
Out[7]: <Book: Book object>

In [8]: Book.objects.create(name= "Banana Book", uploader=User.objects.get(id=1))
Out[8]: <Book: Book object>

In [9]: Book.objects.create(name= "Another book", uploader=User.objects.get(id=3))
Out[9]: <Book: Book object>

In [10]: Book.objects.create(name= "Crazy book", uploader=User.objects.get(id=3))
Out[10]: <Book: Book object>

In [11]: User.objects.get(id=1).liked_books.add(Book.objects.first())

In [12]: User.objects.get(id=1).liked_books.add(Book.objects.last())

In [13]: User.objects.get(id=2).liked_books.add(Book.objects.first())

In [14]: User.objects.get(id=2).liked_books.add(Book.objects.get(id=3))

In [15]: User.objects.get(id=3).liked_books.add(Book.objects.all())
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-c177f5f71870> in <module>()
----> 1 User.objects.get(id=3).liked_books.add(Book.objects.all())

/Users/gwb/Desktop/DojoAssignments/Python/python_stack/myEnvironments/djangoenv/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.pyc in add(self, *objs)
    879             db = router.db_for_write(self.through, instance=self.instance)
    880             with transaction.atomic(using=db, savepoint=False):
--> 881                 self._add_items(self.source_field_name, self.target_field_name, *objs)
    882 
    883                 # If this is a symmetrical m2m relation to self, add the mirror entry in the m2m table

/Users/gwb/Desktop/DojoAssignments/Python/python_stack/myEnvironments/djangoenv/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.pyc in _add_items(self, source_field_name, target_field_name, *objs)
   1026                         .filter(**{
   1027                             source_field_name: self.related_val[0],
-> 1028                             '%s__in' % target_field_name: new_ids,
   1029                         }))
   1030                 new_ids = new_ids - set(vals)

/Users/gwb/Desktop/DojoAssignments/Python/python_stack/myEnvironments/djangoenv/lib/python2.7/site-packages/django/db/models/query.pyc in filter(self, *args, **kwargs)
    792         set.
    793         """
--> 794         return self._filter_or_exclude(False, *args, **kwargs)
    795 
    796     def exclude(self, *args, **kwargs):

/Users/gwb/Desktop/DojoAssignments/Python/python_stack/myEnvironments/djangoenv/lib/python2.7/site-packages/django/db/models/query.pyc in _filter_or_exclude(self, negate, *args, **kwargs)
    810             clone.query.add_q(~Q(*args, **kwargs))
    811         else:
--> 812             clone.query.add_q(Q(*args, **kwargs))
    813         return clone
    814 

/Users/gwb/Desktop/DojoAssignments/Python/python_stack/myEnvironments/djangoenv/lib/python2.7/site-packages/django/db/models/sql/query.pyc in add_q(self, q_object)
   1225         existing_inner = set(
   1226             (a for a in self.alias_map if self.alias_map[a].join_type == INNER))
-> 1227         clause, _ = self._add_q(q_object, self.used_aliases)
   1228         if clause:
   1229             self.where.add(clause, AND)

/Users/gwb/Desktop/DojoAssignments/Python/python_stack/myEnvironments/djangoenv/lib/python2.7/site-packages/django/db/models/sql/query.pyc in _add_q(self, q_object, used_aliases, branch_negated, current_negated, allow_joins, split_subq)
   1251                     child, can_reuse=used_aliases, branch_negated=branch_negated,
   1252                     current_negated=current_negated, connector=connector,
-> 1253                     allow_joins=allow_joins, split_subq=split_subq,
   1254                 )
   1255                 joinpromoter.add_votes(needed_inner)

/Users/gwb/Desktop/DojoAssignments/Python/python_stack/myEnvironments/djangoenv/lib/python2.7/site-packages/django/db/models/sql/query.pyc in build_filter(self, filter_expr, branch_negated, current_negated, can_reuse, connector, allow_joins, split_subq)
   1181             else:
   1182                 lhs = MultiColSource(alias, targets, sources, field)
-> 1183             condition = lookup_class(lhs, value)
   1184             lookup_type = lookup_class.lookup_name
   1185         else:

/Users/gwb/Desktop/DojoAssignments/Python/python_stack/myEnvironments/djangoenv/lib/python2.7/site-packages/django/db/models/lookups.pyc in __init__(self, lhs, rhs)
     17     def __init__(self, lhs, rhs):
     18         self.lhs, self.rhs = lhs, rhs
---> 19         self.rhs = self.get_prep_lookup()
     20         if hasattr(self.lhs, 'get_bilateral_transforms'):
     21             bilateral_transforms = self.lhs.get_bilateral_transforms()

/Users/gwb/Desktop/DojoAssignments/Python/python_stack/myEnvironments/djangoenv/lib/python2.7/site-packages/django/db/models/fields/related_lookups.pyc in get_prep_lookup(self)
     54                 # only one as we don't get to the direct value branch otherwise.
     55                 target_field = self.lhs.output_field.get_path_info()[-1].target_fields[-1]
---> 56                 self.rhs = [target_field.get_prep_value(v) for v in self.rhs]
     57         return super(RelatedIn, self).get_prep_lookup()
     58 

/Users/gwb/Desktop/DojoAssignments/Python/python_stack/myEnvironments/djangoenv/lib/python2.7/site-packages/django/db/models/fields/__init__.pyc in get_prep_value(self, value)
    944         if value is None:
    945             return None
--> 946         return int(value)
    947 
    948     def contribute_to_class(self, cls, name, **kwargs):

TypeError: int() argument must be a string or a number, not 'QuerySet'

In [16]: User.objects.get(id=3).liked_books.add(Book.objects.filter(id__gt=0))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-16-c737a4b65525> in <module>()
----> 1 User.objects.get(id=3).liked_books.add(Book.objects.filter(id__gt=0))

/Users/gwb/Desktop/DojoAssignments/Python/python_stack/myEnvironments/djangoenv/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.pyc in add(self, *objs)
    879             db = router.db_for_write(self.through, instance=self.instance)
    880             with transaction.atomic(using=db, savepoint=False):
--> 881                 self._add_items(self.source_field_name, self.target_field_name, *objs)
    882 
    883                 # If this is a symmetrical m2m relation to self, add the mirror entry in the m2m table

/Users/gwb/Desktop/DojoAssignments/Python/python_stack/myEnvironments/djangoenv/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.pyc in _add_items(self, source_field_name, target_field_name, *objs)
   1026                         .filter(**{
   1027                             source_field_name: self.related_val[0],
-> 1028                             '%s__in' % target_field_name: new_ids,
   1029                         }))
   1030                 new_ids = new_ids - set(vals)

/Users/gwb/Desktop/DojoAssignments/Python/python_stack/myEnvironments/djangoenv/lib/python2.7/site-packages/django/db/models/query.pyc in filter(self, *args, **kwargs)
    792         set.
    793         """
--> 794         return self._filter_or_exclude(False, *args, **kwargs)
    795 
    796     def exclude(self, *args, **kwargs):

/Users/gwb/Desktop/DojoAssignments/Python/python_stack/myEnvironments/djangoenv/lib/python2.7/site-packages/django/db/models/query.pyc in _filter_or_exclude(self, negate, *args, **kwargs)
    810             clone.query.add_q(~Q(*args, **kwargs))
    811         else:
--> 812             clone.query.add_q(Q(*args, **kwargs))
    813         return clone
    814 

/Users/gwb/Desktop/DojoAssignments/Python/python_stack/myEnvironments/djangoenv/lib/python2.7/site-packages/django/db/models/sql/query.pyc in add_q(self, q_object)
   1225         existing_inner = set(
   1226             (a for a in self.alias_map if self.alias_map[a].join_type == INNER))
-> 1227         clause, _ = self._add_q(q_object, self.used_aliases)
   1228         if clause:
   1229             self.where.add(clause, AND)

/Users/gwb/Desktop/DojoAssignments/Python/python_stack/myEnvironments/djangoenv/lib/python2.7/site-packages/django/db/models/sql/query.pyc in _add_q(self, q_object, used_aliases, branch_negated, current_negated, allow_joins, split_subq)
   1251                     child, can_reuse=used_aliases, branch_negated=branch_negated,
   1252                     current_negated=current_negated, connector=connector,
-> 1253                     allow_joins=allow_joins, split_subq=split_subq,
   1254                 )
   1255                 joinpromoter.add_votes(needed_inner)

/Users/gwb/Desktop/DojoAssignments/Python/python_stack/myEnvironments/djangoenv/lib/python2.7/site-packages/django/db/models/sql/query.pyc in build_filter(self, filter_expr, branch_negated, current_negated, can_reuse, connector, allow_joins, split_subq)
   1181             else:
   1182                 lhs = MultiColSource(alias, targets, sources, field)
-> 1183             condition = lookup_class(lhs, value)
   1184             lookup_type = lookup_class.lookup_name
   1185         else:

/Users/gwb/Desktop/DojoAssignments/Python/python_stack/myEnvironments/djangoenv/lib/python2.7/site-packages/django/db/models/lookups.pyc in __init__(self, lhs, rhs)
     17     def __init__(self, lhs, rhs):
     18         self.lhs, self.rhs = lhs, rhs
---> 19         self.rhs = self.get_prep_lookup()
     20         if hasattr(self.lhs, 'get_bilateral_transforms'):
     21             bilateral_transforms = self.lhs.get_bilateral_transforms()

/Users/gwb/Desktop/DojoAssignments/Python/python_stack/myEnvironments/djangoenv/lib/python2.7/site-packages/django/db/models/fields/related_lookups.pyc in get_prep_lookup(self)
     54                 # only one as we don't get to the direct value branch otherwise.
     55                 target_field = self.lhs.output_field.get_path_info()[-1].target_fields[-1]
---> 56                 self.rhs = [target_field.get_prep_value(v) for v in self.rhs]
     57         return super(RelatedIn, self).get_prep_lookup()
     58 

/Users/gwb/Desktop/DojoAssignments/Python/python_stack/myEnvironments/djangoenv/lib/python2.7/site-packages/django/db/models/fields/__init__.pyc in get_prep_value(self, value)
    944         if value is None:
    945             return None
--> 946         return int(value)
    947 
    948     def contribute_to_class(self, cls, name, **kwargs):

TypeError: int() argument must be a string or a number, not 'QuerySet'

In [17]: User.objects.get(id=3).liked_books.add(Book.objects.get(id=1),Book.objects.get(id=2),Book.objects.get(id=3),Book.objects.get(id=4),Book.objects.get(id=5),Book.obj
    ...: ects.get(id=6))

In [18]: User.objects.liked_books.name
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-18-a7c887d4fca5> in <module>()
----> 1 User.objects.liked_books.name

AttributeError: 'Manager' object has no attribute 'liked_books'

In [19]: Book.objects.first().liked_users.first_name
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-19-afcc56a86717> in <module>()
----> 1 Book.objects.first().liked_users.first_name

AttributeError: 'ManyRelatedManager' object has no attribute 'first_name'

In [20]: Book.objects.first().liked_users
Out[20]: <django.db.models.fields.related_descriptors.ManyRelatedManager at 0x1120a15d0>

In [21]: Book.objects.first().liked_users.values()
Out[21]: <QuerySet [{'first_name': u'Grant', 'last_name': u'Brooks', 'created_at': datetime.datetime(2017, 8, 16, 3, 32, 47, 423776, tzinfo=<UTC>), 'updated_at': datetime.datetime(2017, 8, 16, 3, 32, 47, 423991, tzinfo=<UTC>), 'email': u'grant@brooks.com', u'id': 1}, {'first_name': u'Harshada', 'last_name': u'kurahatti', 'created_at': datetime.datetime(2017, 8, 16, 3, 35, 17, 976409, tzinfo=<UTC>), 'updated_at': datetime.datetime(2017, 8, 16, 3, 35, 17, 976464, tzinfo=<UTC>), 'email': u'Harshada@k.com', u'id': 2}, {'first_name': u'Ali', 'last_name': u'Something', 'created_at': datetime.datetime(2017, 8, 16, 3, 37, 21, 179932, tzinfo=<UTC>), 'updated_at': datetime.datetime(2017, 8, 16, 3, 37, 21, 179979, tzinfo=<UTC>), 'email': u'Ali@k.com', u'id': 3}]>

In [22]: Book.objects.first().liked_users.values("first_name")
Out[22]: <QuerySet [{'first_name': u'Grant'}, {'first_name': u'Harshada'}, {'first_name': u'Ali'}]>

In [23]: Book.objects.first().uploader.values("first_name")
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-23-ba5b11a0f3c9> in <module>()
----> 1 Book.objects.first().uploader.values("first_name")

AttributeError: 'User' object has no attribute 'values'

In [24]: Book.objects.first().uploader
Out[24]: <User: User object>

In [25]: Book.objects.first().uploader.values()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-25-fb686ac7eb38> in <module>()
----> 1 Book.objects.first().uploader.values()

AttributeError: 'User' object has no attribute 'values'

In [26]: Book.objects.first().uploader.0.first_name
  File "<ipython-input-26-860c0b719f64>", line 1
    Book.objects.first().uploader.0.first_name
                                  ^
SyntaxError: invalid syntax


In [27]: Book.objects.first().uploader.[0].first_name
  File "<ipython-input-27-fa72e42849cc>", line 1
    Book.objects.first().uploader.[0].first_name
                                  ^
SyntaxError: invalid syntax


In [28]: Book.objects.first().uploader[0].first_name
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-28-aacd8b5d88f9> in <module>()
----> 1 Book.objects.first().uploader[0].first_name

TypeError: 'User' object does not support indexing

In [29]: u = Book.objects.first().uploader

In [30]: for x in u:
    ...:     x.first_name
    ...:     
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-30-a8400d4a1b8b> in <module>()
----> 1 for x in u:
      2     x.first_name
      3 

TypeError: 'User' object is not iterable

In [31]: u.first_name
Out[31]: u'Harshada'

In [32]: u = Book.objects.first().uploader.first_name

In [33]: Book.objects.first().uploader.first_name
Out[33]: u'Harshada'

In [34]: Book.object.get(id=2).liked_users.values(first_name)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-34-ae657209ba66> in <module>()
----> 1 Book.object.get(id=2).liked_users.values(first_name)

AttributeError: type object 'Book' has no attribute 'object'

In [35]: Book.objects.get(id=2).liked_users.values(first_name)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-35-52231de12a33> in <module>()
----> 1 Book.objects.get(id=2).liked_users.values(first_name)

NameError: name 'first_name' is not defined

In [36]: Book.objects.get(id=2).liked_users.values("first_name")
Out[36]: <QuerySet [{'first_name': u'Ali'}]>

In [37]: Book.objects.get(id=2).uploader.first_name
Out[37]: u'Harshada'

In [38]: Book.objects.get(id=2).liked_users.first_name
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-38-cf6521418576> in <module>()
----> 1 Book.objects.get(id=2).liked_users.first_name

AttributeError: 'ManyRelatedManager' object has no attribute 'first_name'

In [39]: Book.objects.get(id=1).liked_users.values("first_name")
Out[39]: <QuerySet [{'first_name': u'Grant'}, {'first_name': u'Harshada'}, {'first_name': u'Ali'}]>

In [40]: b = Book.objects.get(id=1).liked_users.values("first_name")

In [41]: for x in b:
    ...:     print x
    ...:     
{'first_name': u'Grant'}
{'first_name': u'Harshada'}
{'first_name': u'Ali'}

In [42]: for x in b:
    ...:     print x.first_name
    ...:     
    ...:     
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-42-241e912b7c48> in <module>()
      1 for x in b:
----> 2     print x.first_name
      3 
      4 

AttributeError: 'dict' object has no attribute 'first_name'

In [43]: b = Book.objects.get(id=1).liked_users.values()

In [44]: for x in b:
    ...:     print x.first_name
    ...:     
    ...:     
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-44-241e912b7c48> in <module>()
      1 for x in b:
----> 2     print x.first_name
      3 
      4 

AttributeError: 'dict' object has no attribute 'first_name'

In [45]: 
